baseURL = "https://garten.familykaufmann.de/"
languageCode = "de-de"
title = "Unser Gartenblog"
theme = "hugo-vitae"
paginate = 5
enableRobotsTXT = false
copyright = "© 2021 Andrea & David | [Vitae](https://github.com/dataCobra/hugo-vitae) theme for [Hugo](https://gohugo.io)"
enableEmoji = true

[permalinks]
    posts = "/:year/:month/:title/"

[taxonomies]
    tag = "tags"
    series = "series"

[params]
    keywords = ["Garten", "Pflanzen", "Saison", "Hobby"]
    description = "Dieser simple Blog dokumentiert unsere Fortschritte und Gedanken im Garten"
    pagetitle = "Unser Gartenblog"
    subtitle = "Planen, pflanzen, pflegen, ernten, nutzen"
    math = false
    avatar = "/img/tree.jpg"
    listAuthor = true
    customCSS = "css/perfundo.with-icons.css"

[params.customJS]
enabled = true
src = "/js/bundle.min.js"
#integrity = "asd"

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/davidkaufmann/garden_blog"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"
